import {LOCALES} from "../locales";

export const Students = {
    [LOCALES.RUSSIAN]: {
        "studentsDes2": "-  заявление на имя ректора;",
        "studentsDes3": "-  оригинал и копию паспорта, его заверенный перевод на русский язык;",
        "studentsDes4": "-  копию первичной визы и регистрации, соответствующих требованиям законодательства КР;",
        "studentsDes5": "-  оригинал и копию документа о соответствующем уровне образования с указанием изученных предметов и оценок, его заверенный перевод на русский язык;",
        "studentsDes6": "-  справку об эквивалентности уровня образования, выданную МОиН КР;",
        "studentsDes7": "-  медицинскую справку (форма N° 086/у) с результатами исследований на ВИЧ, вирусные гепатиты В, С, Д, малярию, и результатом флюорографии;",
        "studentsDes8": "-  8 фотографий размером 3*4 см;",
        "studentsDes9": "-  квитанция об оплате приема документов;",
        "studentsDes10": "-  другие документы, необходимые документы по требованиям страны происхождения для приема иностранных граждан в зарубежные медицинские университеты.",
        "studentsDesc": "Иностранные граждане, желающие обучаться в МУМН на английском языке, могут поступить лишь на факультет «Лечебное дело с английским языком обучения» на 5-ти летнюю программу.\n" +
            "  Уровень образования поступающих не может быть ниже среднего общего 12-ти летнего образования с обязательным изучением профилирующих предметов химия и биология и должен быть подтвержден справкой об эквивалентности уровня образования, выданной МОиН КР, а также результат полученных итоговых баллов не должен быть ниже требования, установленного органами образования страны происхождения для поступления в зарубежные медицинские университеты.\n" +
            "  После прибытия, иностранный гражданин представляет легализованные в установленном законодательством КР порядке следующие документы:",
        "studentsTit": "Для студентов ",
        "students2Desc2": "-  предоставление всех необходимых документов;",
        "students2Desc3": "-  успешная сдача вступительных испытаний;",
        "students2Desc4": "-  оформление Договора с физическими и (или) юридическими лицами;",
        "students2Desc5": "-  оплата суммы контракта.",
        "students2Desc": "Все переводы на русский язык должны быть выполнены на имя и фамилию, указанные во въездной визе.Дата, место и форма проведения вступительных испытаний для иностранных граждан определяются Приемной комиссией.Вступительные испытания могут проходить в виде бланочного тестирования в письменной форме с компьютерной обработкой по профилирующим предметам (химия, биология) или устного собеседования.Зачисление иностранных граждан производится в сроки и в порядке, установленными Правилами приема в МУМН и МОиН при соблюдении следующих условий.",
        "students3Desc": " Зачисление иностранных граждан в МУМН оформляется приказом ректора. Особенности порядка временного пребывания иностранных граждан в МУМН. Иностранные граждане, поступившие и обучающиеся в МУМН, считаются временно пребывающими в КР. Работа, связанная с оформлением визовой поддержки, временной регистрации и продление виз для иностранных граждан осуществляется инспектором по паспортно-визовой работе с иностранными гражданами Отдела международных связей МУМН (далее ОМС).По приглашению МУМН иностранные граждане обязаны прибыть в КР только на учебу в МУМН." +
            " По прибытию в КР иностранный гражданин в установленном порядке обязан зарегистрировать свои паспорта или заменяющие их документы в паспортном столе по месту проживания в течение 3-х рабочих дней с момента пересечения Государственной границы КР на срок действия текущей визы. Для этого им необходимо сдать нотариальное соглашение владельца квартиры или справку о проживании в общежитии МУМН для временной регистрации иностранного студента. Гражданам иностранных государств, для которых применён принцип взаимности в установленном законом порядке в силу международных договоров, процедура регистрации производится по истечению срока, предусмотренного в законодательстве КР." +
            "  Иностранным студентам до окончания действующей визы за один месяц, необходимо подавать нижеследующие документы:",
        "students3Desc2": "-  справка из деканата, подтверждающая обучение иностранного студента на данном факультете (1 экз.);",
        "students3Desc3": "-  оригинал паспорта;",
        "students3Desc4": "-  копия последней визы с регистрацией (2 экз.);",
        "students3Desc5": "-  заполненная анкета с фотографией размером 3*4 см (2 экз.);",
        "students3Desc6": "-  нотариальное соглашение владельца квартиры для временной регистрации иностранного студента....Продления срока визы обязывает иностранного студента продлевать срок действия регистрации в течении одного рабочего дня.",
        "students4Desc": "Иностранный студент должен выехать из республики по истечении определенного им срока пребывания, то есть после окончания обучения, а также при досрочном исключении из числа студентов.Организация процесса обучения иностранных студентов.Порядок отчисления иностранных студентов из МУМН .  МУМН имеет право отчислять иностранных студентов в следующих случаях:",
        "students4Desc1": "-  за академическую неуспеваемость;",
        "students4Desc2": "-  за нарушение учебной дисциплины (невыполнение графика учебного процесса, утерю связи с вузом, невыход из академического отпуска по окончании его срока);",
        "students4Desc3": "-  за нарушение правил внутреннего распорядка, положений настоящего Устава, Этического кодекса, правил проживания в общежитии;",
        "students4Desc4": "-  в связи с непрохождением государственной итоговой аттестации;",
        "students4Desc5": "-  невыполнение условий договора и по другим причинам.",
        "students5Desc": " Отчисление иностранного студента из МУМН оформляется приказом проректора по учебной работе." +
            " Декан обязан обеспечить явку иностранного отчисленного студента в ОМС для оформления выездной визы." +
            "ОМС осуществляет все необходимые процедуры, связанные с дальнейшим пребыванием на территории КР отчисленного иностранного гражданина" +
            "  ОМС также подготавливает письма, уведомляющие об отчислении иностранного студента для направления в:",
        "students5Desc1": " - Департамент консульской службы Министерства иностранных дел Кыргызской Республики (ДКС МИД КР); ",
        "students5Desc2": "  - Государственный Комитет Национальной Безопасности Кыргызской Республики (ГКНБ КР);",
        "students5Desc3": " - Министерство внутренних дел Кыргызской Республики (МВД КР); ",
        "students6Desc": "    При досрочном исключении из МУМН или после окончания обучения иностранный студент обязан покинуть пределы КР, до конца истечения срока последней (выездной) визы." +
            " МУМН не несет ответственности в случае несвоевременного предоставления документов для регистрации. В случае задержки документов иностранный гражданин несет административное наказание в виде оплаты штрафа, в размере, установленном законодательством КР. Права и обязанности иностранных студентов" +
            " Ответственность иностранных студентов определяется Договором, который имеет юридическую силу, определяет права и обязанности обеих сторон, а также правила разрешения спорных вопросов, возникающих в процессе его реализации." +
            " За невыполнение учебных планов и другие нарушения обязанностей, предусмотренных Уставом МУМН, к иностранным студентам могут быть применены меры дисциплинарного воздействия вплоть до исключения из университета." +
            "  Иностранные студенты, совершившие преступления, административные или иные правонарушения, привлекаются к ответственности в соответствии с действующим законодательством КР." +
            "  Иностранные студенты не имеют права проходить военную подготовку в Кыргызской Республике. По завершению обучения иностранные граждане получают документ об образовании государственного образца соответствующего уровня." +
            "   Иностранные граждане имеют право на: ",
        "students6Desc2": " -  получение образования на уровне государственных образовательных стандартов Кыргызской Республики;    ",
        "students6Desc3": " -  участие в научно-исследовательских работах, конференциях, симпозиумах и других мероприятиях;    ",
        "students6Desc4": "  -  публикации своих работ;   ",
        "students6Desc5": " -  пользование учебными помещениями и оборудованием, библиотеками, спортивными сооружениями, учебными, научными и другими подразделениями в порядке, определяемом Уставом МУМН.    ",
        "students7Desc": "          Социально-бытовое обеспечение иностранных студентов",
        "students7Desc2": "    МУМН оказывает содействие иностранному студенту по обеспечению его безопасности, правовой защиты и визовой, социальной поддержки.",
        "students7Desc3": "МУМН не берет на себя никаких расходов по страхованию жизни иностранных студентов и их имущества, это обязанность самого иностранного гражданина. Все виды медицинской помощи предоставляются иностранным студентам по страховому полису или на договорной основе за счет их личных средств в медицинском центре МУМН ",
        "students7Desc4": " Работа с иностранными студентами   На каждом факультете имеется ответственное лицо - куратор факультета, который непосредственно подчиняется декану факультета и заведующему отдела воспитательной и организационно-массовой работы.",
        "students7Desc5": "Куратор назначается на должность и освобождается от должности приказом ректора/проректора по государственному языку и воспитательной работе МУМН по представлению декана факультета/ заведующего отдела воспитательной и организационно-массовой работы, из числа наиболее опытных педагогических работников.  ",
        "students7Desc6": " Работа куратора направлена на воспитание обучающегося в коллективе и организацию учебно-воспитательного процесса факультета/в учебной группе, а также создание благоприятных условий для индивидуального развития и нравственного формирования студентов. ",
        "students7Desc7": "Куратор факультета проводит социально-адаптационную, воспитательную работу, следит за состоянием морально-психологического климата, организует культурно-массовые мероприятия с участием иностранных студентов, контроль учебной работы и вне... ",
        "students7Desc8": "Прием иностранных граждан из стран дальнего зарубежья осуществляется не посредственно официального представителя МУМН, который привлекает иностранных абитуриентов на обучение. Представителями МУМН и партнерами МУМН «Ал Мадина Эдьюкейшн Эдвайзерс» работает на основании подписанного соглашения о сотрудничестве с МУМН, которое дает ему право набирать абитуриентов для поступления в соответствии с квотой, выделенной МОиН КР. Представители МУМН и партнеры МУМН «Ал Мадина Эдьюкейшн Эдвайзерс» подают заявку для оформления визовой поддержки на иностранного абитуриента, которая готовится представителями МУМН и партнерами МУМН «Ал Мадина Эдьюкейшн Эдвайзерс» и подают в Департамент Консульской Службы МИД КР. Иностранный гражданин обращается в посольство КР в стране происхождения для получения учебной визы КР. После прибытия в КР представители МУМН и партнеры МУМН «Ал Мадина Эдьюкейшн Эдвайзерс» помогают собрать необходимые документы для поступления в МУМН. После этого иностранный абитуриент допускается к сдаче вступительного экзамена, который проводится методом бланочного тестирования с компьютерной обработкой  результатов или посредством устной  сдачи вступительного экзамена. В случае если иностранный абитуриент успешно сдает вступительные испытания, его зачисляют на учебу и заключается договор на обучение с МУМН.",


    },
    [LOCALES.KYRGYZ]: {
        "studentsDes2": "- ректордун атына жазылган арыз;",
        "studentsDes3": "- паспорттун түп нускасы жана көчүрмөсү, анын орус тилине күбөлөндүрүлгөн котормосу;",
        "studentsDes4": "- Кыргыз Республикасынын мыйзамдарынын талаптарына жооп берген негизги визанын жана каттоонун көчүрмөсү;",
        "studentsDes5": "- окулган предметтерди жана бааларды көрсөтүү менен билиминин тиешелүү деңгээли жөнүндө документтин түп нускасы жана көчүрмөсү, анын орус тилине күбөлөндүрүлгөн котормосу;",
        "studentsDes6": "- Кыргыз Республикасынын Билим берүү жана илим министрлиги тарабынан берилген билим деңгээлинин эквиваленттүүлүгү жөнүндө күбөлүк;",
        "studentsDes7": "- ВИЧ, вирустук гепатит В, С, D, безгек боюнча изилдөөлөрдүн натыйжалары жана флюорографиянын жыйынтыгы менен медициналык маалымкат (N ° 086/y формасы);",
        "studentsDes8": "- 3*4 см өлчөмүндөгү 8 сүрөт;",
        "studentsDes9": "- документтерди кабыл алуу үчүн төлөм квитанциясы",
        "studentsDes10": "- башка документтер, чет өлкөлүк жарандарды чет өлкөлүк медициналык университеттерге кабыл алуу үчүн келип чыккан өлкөнүн талаптары үчүн зарыл документтер.",
        "studentsDesc": "ЭМИУда англис тилинде окууну каалаган чет элдик жарандар 5 жылдык программа боюнча англис тилинде окутуу тили болгон жалпы медицина факультетине гана кире алышат.«Абитуриенттердин билим деңгээли химия жана биология боюнча негизги предметтерди милдеттүү түрдө окутуу менен жалпы 12 жылдык орто билимден төмөн болушу мүмкүн эмес жана Билим берүү жана илим министрлиги тарабынан берилген билим деңгээлинин эквиваленттүүлүгү жөнүндө маалымкат менен ырасталышы керек. Кыргыз Республикасынын, жана алынган жыйынтык баллдардын натыйжасы чет өлкөлүк медициналык ЖОЖдорго кабыл алуу үчүн келип чыккан өлкөнүн билим берүү органдары тарабынан белгиленген талаптардан төмөн болбоого тийиш. Чет өлкөлүк жаран келгенден кийин Кыргыз Республикасынын мыйзамдарында белгиленген тартипте легалдаштырылган төмөнкү документтерди тапшырат:",
        "studentsTit": "Студенттер үчүн",
        "students2Desc2": "- бардык керектүү документтерди тапшыруу;",
        "students2Desc3": "кирүү экзамендерин ийгиликтүү тапшыруу;",
        "students2Desc4": "- жеке жана (же) юридикалык жактар ​​менен келишимди түзүү;",
        "students2Desc5": "- контракттын суммасын төлөө.",
        "students2Desc": "Орус тилине бардык котормолор кирүү визасында көрсөтүлгөн аты жана фамилиясында жасалышы керек. Чет өлкөлүк жарандар үчүн кирүү экзамендерин өткөрүү күнү, орду жана формасы кабыл алуу комиссиясы тарабынан аныкталат. Кирүү сынактары төмөнкү формада болушу мүмкүн: негизги предметтер боюнча (химия, биология) компьютердик иштетүү менен жазуу жүзүндөгү бланк тест же оозеки маектешүүлөр.Чет өлкөлүк жарандар Билим берүү жана илим министрлигине жана Билим берүү министрлигине кабыл алуунун эрежелеринде белгиленген мөөнөттө жана тартипте кабыл алынат. Төмөнкү шарттарды сактоо менен илим.",
        "students3Desc": "Чет элдик жарандарды ЭМИУга кабыл алуу ректордун буйругу менен жол-жоболоштурулат. Чет өлкөлүк жарандардын ЭМИУда убактылуу жүрүү тартибинин өзгөчөлүктөрү. ЭМИУгa кирген жана окуган чет өлкөлүк жарандар убактылуу деп эсептелет. Чет өлкөлүк жарандарга визалык колдоо көрсөтүү, визаларды убактылуу каттоо жана узартуу менен байланышкан иштерди ЭМИУнун Эл аралык байланыштар башкармалыгынын (мындан ары ОМБ) чет өлкөлүк жарандар менен паспорттук-визалык иш боюнча инспектору жүргүзөт. ММУнун чакыруусу боюнча, чет өлкөлүк жарандар Кыргыз Республикасына МУМНда окуу үчүн гана келүүгө тийиш». +\n" +
            "            «Чет өлкөлүк жаран Кыргыз Республикасына келгенден кийин Кыргыз Республикасынын Мамлекеттик чек арасын кесип өткөн учурдан тартып 3 жумушчу күндүн ичинде өзүнүн паспортун же аны алмаштыруучу документтерди жашаган жери боюнча паспорттук столдо белгиленген тартипте каттатууга милдеттүү. Учурдагы визанын мөөнөтү.Бул үчүн алар батирдин ээси менен нотариалдык макулдашууну же чет өлкөлүк студентти убактылуу каттоо үчүн ЭМИУнун жатаканасында жашаган жеринен маалымкатты тапшырышы керек.. Принципи бар чет мамлекеттин жарандары. өз ара аракеттенүү эл аралык келишимдерде мыйзамда белгиленген тартипте колдонулат, каттоо жол-жобосу Кыргыз Республикасынын мыйзамдарында каралган мөөнөт аяктагандан кийин жүргүзүлөт.». \n" +
            "            \"Чет элдик студенттер жарактуу визанын мөөнөтү аяктаганга чейин бир ай мурун төмөнкү документтерди тапшырышы керек:",

        "students3Desc2": "- чет өлкөлүк студенттин ушул факультетте окуганын тастыктаган деканаттан маалымкат (1 нуска);",
        "students3Desc3": "- паспорттун оригиналы;",
        "students3Desc4": "- каттоо менен акыркы визанын көчүрмөсү (2 нуска);",
        "students3Desc5": "- 3*4 см (2 нуска) сүрөтү менен толтурулган анкета;",
        "students3Desc6": "- чет өлкөлүк студентти убактылуу каттоо үчүн батирдин ээсинин нотариалдык макулдашуусу .... Визаны узартуу чет өлкөлүк студентти бир жумушчу күндүн ичинде каттоону узартууга милдеттендирет.",
        "students4Desc": "Чет өлкөлүк студент өзү белгилеген мөөнөт аяктагандан кийин, башкача айтканда окуу жайды аяктагандан кийин, ошондой эле студенттердин катарынан мөөнөтүнөн мурда чыгарылган учурда республикадан чыгып кетиши керек. Окуу процессин уюштуруу чет элдик студенттер",
        "students4Desc1": "- академиялык ийгиликсиздик үчүн;",
        "students4Desc2": "- окуу тартибин бузгандыгы үчүн (окуу процессинин графигин аткарбоо, ЖОЖ менен байланышты жоготуу, анын мөөнөтү аяктагандан кийин академиялык өргүүдөн чыгуу);",
        "students4Desc3": "- ички тартипти, ушул Уставдын жоболорун, Этика кодексин, жатаканада жашоо эрежелерин бузгандыгы үчүн;",
        "students4Desc4": "- мамлекеттик жыйынтыктоочу аттестациядан өтпөй калгандыгына байланыштуу;",
        "students4Desc5": "- келишимдин шарттарын аткарбоо жана башка себептерден улам.",
        "students5Desc": "Чет элдик студентти ЭМИУдан чыгаруу окуу иштери боюнча проректордун буйругу менен таризделет.\" \n" +
            "            Декан окуудан чыгарылган чет өлкөлүк студенттин чыгуу визасын берүү үчүн ОМСке келишин камсыз кылууга милдеттүү. \n" +
            "            \"ОМС чыгарылып кеткен чет өлкөлүк жарандын Кыргыз Республикасынын аймагында андан ары болушуна байланыштуу бардык зарыл процедураларды жүргүзөт\" \n" +
            "            \"OMS ошондой эле чет өлкөлүк студенттин окуудан чыгарылгандыгы жөнүндө каттарды даярдайт:",
        "students5Desc1": "- Кыргыз Республикасынын Тышкы иштер министрлигинин Консулдук кызмат башкармалыгы (КР ТИМи);",
        "students5Desc2": "- Кыргыз Республикасынын Улуттук коопсуздук мамлекеттик комитети (КР УКМК);",
        "students5Desc3": "- Кыргыз Республикасынын Ички иштер министрлиги (КР ИИМ);",
        "students6Desc": "ЭМИУдан мөөнөтүнөн мурда чыгарылган же окууну аяктагандан кийин, чет өлкөлүк студент акыркы (чыгуу) визасынын мөөнөтү аяктаганга чейин Кыргыз Республикасынан чыгып кетүүгө милдеттүү.\" \n" +
            "            \"ЭМИУ документтерин каттоого өз убагында бербеген учурда жоопкерчилик тартпайт. Документтерди кечиктирген учурда чет өлкөлүк жаран Кыргыз Республикасынын мыйзамдарында белгиленген өлчөмдө айып пул төлөө түрүндөгү административдик айыпка тартылат. Чет өлкөлүк студенттердин укуктары жана милдеттери» \n" +
            "            «Чет элдик студенттердин жоопкерчилиги келишимде аныкталат, ал юридикалык жактан милдеттүү, эки тараптын тең укуктарын жана милдеттерин, ошондой эле аны ишке ашыруу процессинде келип чыккан талаш-тартыштарды чечүү эрежелерин аныктайт». \n" +
            "            «Окуу пландарын аткарбагандыгы жана ЭМИУнун Уставында каралган милдеттерди башка бузгандыгы үчүн чет өлкөлүк студенттерге университеттен чыгарууга чейин тартиптик жаза чаралары колдонулушу мүмкүн». \n" +
            "            Кылмыш, административдик же башка укук бузууларды жасаган чет өлкөлүк студенттер Кыргыз Республикасынын колдонуудагы мыйзамдарына ылайык жоопкерчиликке тартылышат”. \n" +
            "            \"Чет элдик студенттер Кыргыз Республикасынын аймагында аскердик даярдыктан өтүүгө укугу жок. Окууну аяктагандан кийин чет өлкөлүк жарандар мамлекет тарабынан таанылган тиешелүү деңгээлдеги билими тууралуу аттестат алышат\". \n" +
            "            \"Чет өлкөлүк жарандар төмөнкүлөргө укуктуу:",
        "students6Desc2": "- Кыргыз Республикасынын мамлекеттик билим берүү стандарттарынын деңгээлинде билим алуу;",
        "students6Desc3": "- илимий долбоорлорго, конференцияларга, симпозиумдарга жана башка иш-чараларга катышуу;",
        "students6Desc4": "- алардын эмгектеринин басылмалары;",
        "students6Desc5": "- окуу кабинеттерин жана жабдууларын, китепканаларды, спорттук имараттарды, окуу, илимий жана башка бөлүмдөрдү МУМУнун Уставында аныкталган тартипте пайдалануу.",
        "students7Desc": "Чет элдик студенттердин социалдык жыргалчылыгы",
        "students7Desc2": "ЭМИУ чет өлкөлүк студентке анын коопсуздугун камсыз кылууга, укуктук жактан коргоого жана виза, социалдык жактан колдоо көрсөтүүгө жардам берет.",
        "students7Desc3": "ЭМИУ чет өлкөлүк студенттердин өмүрүн жана алардын мүлкүн камсыздандыруу боюнча эч кандай чыгымдарды өзүнө албайт, бул чет өлкөлүк жарандын жоопкерчилигинде. Медициналык жардамдын бардык түрлөрү чет өлкөлүк студенттерге камсыздандыруу полиси боюнча же келишимдик негизде берилет. ЭМИУ   медициналык борборунда алардын жеке каражаттарынын эсебинен",
        "students7Desc4": "Чет элдик студенттер менен иштөө Ар бир факультетте жооптуу адам - ​​факультеттин куратору болот, ал факультеттин деканына жана окуу жана уюштуруу-массалык иштер бөлүмүнүн башчысына түздөн-түз баш ийет.",
        "students7Desc5": "Куратор факультеттин деканынын/кафедра башчысынын сунушу боюнча Билим берүү жана илим министрлигинин ректорунун/мамлекеттик тил жана тарбия иштери боюнча проректорунун буйругу менен кызматка дайындалат жана бошотулат. окуу-тарбиялык жана уюштуруу-массалык иштерди, тажрыйбалуу мугалимдердин ичинен.",
        "students7Desc6": "Куратордун иши студентти коллективде тарбиялоого жана факультеттин/окуу тобунун окуу процессин уюштурууга, ошондой эле студенттердин инсандык өнүгүүсү жана моралдык жактан калыптануусу үчүн жагымдуу шарттарды түзүүгө багытталган.",
        "students7Desc7": "Факультеттин куратору социалдык адаптациялоо, тарбиялоо иштерин жүргүзөт, моралдык-психологиялык климаттын абалына мониторинг жүргүзөт, чет элдик студенттердин катышуусунда маданий иш-чараларды уюштурат, окуу-тарбия иштерине жана тышкаркы.",
        "students7Desc8": "\"Чет өлкөлөрдөн келген чет элдик жарандарды кабыл алуу түздөн-түз ЭМИУ расмий өкүлү тарабынан ишке ашырылат, ал окууга чет өлкөлүк абитуриенттерди тартат. ЭМИУ өкүлдөрү жана ЭМИУ өнөктөштөрү\" Al Madina Education Advisers \"иштешет. Кыргыз Республикасынын Билим берүү жана илим министрлиги тарабынан бөлүнгөн квотага ылайык кабыл алуу үчүн абитуриенттерди кабыл алуу укугун берген ЭМИУ менен кол коюлган кызматташуу келишиминин негизинде ЭМИУнун өкүлдөрү жана ЭМИУ өнөктөштөрү \"Al Madina Education Advisers\" \" Чет өлкөлүк өтүнмө ээсине визалык колдоо көрсөтүү үчүн кайрылыңыз, аны ЭМИУ өкүлдөрү жана \"Al Madina Education\" ЭМИУнун өнөктөштөрү жана Кыргыз Республикасынын Тышкы иштер министрлигинин Консулдук кызмат департаментинин кеңешчилери даярдашат. Чет өлкөлүк жаран кайрылат. Кыргыз Республикасына окуу визасын алуу үчүн келген өлкөдөгү Кыргыз Республикасынын элчилигине Кыргыз Республикасына келгенден кийин Эл аралык байланыштар министрлигинин өкүлдөрү жана Тышкы иштер министрлигинин Эл аралык байланыштар министрлигинин өнөктөштөрү Кыргыз Республикасынын иштери Кыргыз Республикасынын Тышкы иштер министрлигине кабыл алуу үчүн зарыл болгон документтерди чогултууга жардам берет. абитуриентке кирүү экзаменин тапшырууга уруксат берилет, ал жыйынтыктарды компьютерде иштеп чыгуу менен бланктык тестирлөө ыкмасы менен же кирүү экзаменин оозеки тапшыруу жолу менен жүргүзүлөт. Эгерде чет өлкөлүк абитуриент кирүү экзамендерин ийгиликтүү тапшырса, ал окууга кабыл алынат жана ЭМИУ менен окуу келишими түзүлөт.",
    },
    [LOCALES.ENGLISH]: {
        "studentsDes2": "- application addressed to the rector;\n",
        "studentsDes3": "- original and copy of the passport, its certified translation into Russian;\n",
        "studentsDes4": "- a copy of the primary visa and registration that meet the requirements of the legislation of the Kyrgyz Republic;\n",
        "studentsDes5": "- the original and a copy of the document on the appropriate level of education, indicating the subjects studied and grades, its certified translation into Russian;",
        "studentsDes6": "- a certificate of the equivalence of the level of education issued by the Ministry of Education and Science of the Kyrgyz Republic;\n",
        "studentsDes7": "- medical certificate (form N ° 086 / y) with the results of tests for HIV, viral hepatitis B, C, D, malaria, and the result of fluorography;\n",
        "studentsDes8": "- 8 photographs measuring 3 * 4 cm;\n",
        "studentsDes9": "- a receipt for payment of documents acceptance;\n",
        "studentsDes10": "- other documents, necessary documents for the requirements of the country of origin for the admission of foreign citizens to foreign medical universities.\n",
        "studentsDesc": "Foreign citizens wishing to study at International University of Medicine and Science (IUMS) in English can only enter the faculty of General Medicine with English as the language of instruction for a 5-year program. The level of education of applicants cannot be lower than the secondary general 12-year education with the compulsory study of major subjects in chemistry and biology and must be confirmed by a certificate of the equivalence of the level of education issued by the Ministry of Education and Science of the Kyrgyz Republic, and the result of the final scores received must not be lower than the requirements established by the authorities education of the country of origin for admission to foreign medical universities.\n" +
            "After arrival, a foreign citizen submits the following documents legalized in accordance with the legislation of the Kyrgyz Republic:",
        "studentsTit": "For Students ",
        "students2Desc2": "- provision of all necessary documents;\n",
        "students2Desc3": "- successful passing of entrance examinations;\n",
        "students2Desc4": "- execution of the Agreement with individuals and (or) legal entities;\n",
        "students2Desc5": "- payment of the contract amount.\n",
        "students2Desc": "All translations into Russian must be made in the name and surname specified in the entry visa. The date, place and form of entrance examinations for foreign citizens are determined by the Admissions Committee. Entrance examinations can take the form of a blank test in writing with computer processing in major subjects (chemistry, biology) or oral interview. The enrollment of foreign citizens is carried out in the terms and in the manner established by the Rules for admission to the International University of Medicine and Science and the Ministry of Education and Science, subject to the following conditions:\n",
        "students3Desc": "The enrollment of foreign citizens in the IUMS is formalized by the order of the rector. Features of the procedure for temporary stay of foreign citizens in the IUMS. Foreign citizens who entered and studied at the IUMS are considered to be temporarily staying in the Kyrgyz Republic. Work related to obtaining visa support, temporary registration and extension of visas for foreign citizens is carried out by the inspector for passport and visa work with foreign citizens of the Department of International Relations of the IUMS (hereinafter DIR). At the invitation of the IUMS, foreign citizens must come to the Kyrgyz Republic only to study at the IUMS. Upon arrival in the Kyrgyz Republic, a foreign citizen in the prescribed manner is obliged to register his passports or documents replacing them at the passport office at the place of residence within 3 working days from the moment of crossing the State border of the Kyrgyz Republic for the duration of the current visa. To do this, they need to submit a notarial agreement of the owner of the apartment or a certificate of residence in the IUMS hostel for the temporary registration of a foreign student.Citizens of foreign states for whom the principle of reciprocity is applied in accordance with the procedure established by law by virtue of international treaties, the registration procedure is carried out upon the expiration of the period provided for in the legislation of the Kyrgyz Republic. Foreign students, before the expiration of a valid visa one month in advance, must submit the following documents:\n",
        "students3Desc2": "- a certificate from the dean's office confirming the study of a foreign student at this faculty (1 copy);\n",
        "students3Desc3": "- original passport;\n",
        "students3Desc4": "- copy of the last visa with registration (2 copies);\n",
        "students3Desc5": "- a completed questionnaire with a photograph of 3 * 4 cm (2 copies);\n",
        "students3Desc6": "- notarial agreement of the owner of the apartment for the temporary registration of a foreign student .... Visa extension obliges the foreign student to renew the registration validity within one working day.\n",
        "students4Desc": "A foreign student must leave the republic after the expiration of the period of stay specified by him, that is, after graduation, as well as in case of early expulsion from the number of students. Organization of the learning process for foreign students. The procedure for expulsion of foreign students from IUMS. IUMS has the right to expel foreign students in the following cases:\n",
        "students4Desc1": "- for violation of academic discipline (failure to meet the schedule of the educational process, loss of connection with the university, absence from academic leave at the end of its term);\n",
        "students4Desc2": "- for violation of internal regulations, provisions of this Charter, Code of Ethics, rules of residence in a hostel;\n",
        "students4Desc3": "- due to the failure to pass the state final certification;\n",
        "students4Desc4": "- failure to comply with the terms of the contract and for other reasons.\n",
        "students4Desc5": "- due to the failure to pass the state final certification;",
        "students5Desc": "The expulsion of a foreign student from the IUMS is formalized by the order of the Vice-Rector for Academic Affairs. The dean is obliged to ensure the appearance of a foreign expelled student at the DIR for issuing an exit visa. DIR carries out all the necessary procedures related to the further stay in the territory of the Kyrgyz Republic of an expelled foreign citizen DIR also prepares letters notifying the expulsion of a foreign student to be sent to:\n",
        "students5Desc1": "- Department of Consular Service of the Ministry of Foreign Affairs of the Kyrgyz Republic (DCS MFA KR);\n",
        "students5Desc2": "- State Committee for National Security of the Kyrgyz Republic (SCNS KR);\n",
        "students5Desc3": "- Ministry of Internal Affairs of the Kyrgyz Republic (Ministry of Internal Affairs of the Kyrgyz Republic);\n",
        "students6Desc": "In case of early expulsion from the IUMS or after graduation, the foreign student is obliged to leave the Kyrgyz Republic, before the end of the expiration of the last (exit) visa. IUMS is not responsible in case of late submission of documents for registration. In case of delay in documents, a foreign citizen bears an administrative penalty in the form of payment of a fine, in the amount established by the legislation of the Kyrgyz Republic.\n" +
            "Rights and obligations of foreign students The responsibility of foreign students is determined by the Agreement, which is legally binding, defines the rights and obligations of both parties, as well as the rules for resolving disputes arising in the process of its implementation. For non-fulfillment of curricula and other violations of the obligations stipulated by the Charter of the IUMS, disciplinary measures may be applied to foreign students, up to and including expulsion from the university.\n" +
            "Foreign students who have committed crimes, administrative or other offenses are brought to justice in accordance with the current legislation of the Kyrgyz Republic. Foreign students are not eligible for military training in the Kyrgyz Republic. Upon completion of training, foreign citizens receive a state education certificate of the appropriate level.\n" +
            "Foreign citizens have the right to:",
        "students6Desc2": "- getting education at the level of state educational standards of the Kyrgyz Republic;\n",
        "students6Desc3": "- participation in research projects, conferences, symposia and other events;\n",
        "students6Desc4": "- publication of their works;\n",
        "students6Desc5": "- use of classrooms and equipment, libraries, sports facilities, educational, scientific and other departments in the manner determined by the Charter of the IUMS.\n",
        "students7Desc": "Social welfare of foreign students\n",
        "students7Desc2": "\t•\tIUMS assists a foreign student in ensuring his safety, legal protection and visa, social support.\n",
        "students7Desc3": "\t•\tIUMS does not undertake any expenses for life insurance of foreign students and their property, this is the responsibility of the foreign citizen himself. All types of medical care are provided to foreign students under an insurance policy or on a contractual basis at the expense of their personal funds in the medical center of the IUMS\n",
        "students7Desc4": "\t•\tWorking with foreign students Each faculty has a responsible person - the faculty curator, who is directly subordinate to the dean of the faculty and the head of the department of educational and organizational-mass work.\n",
        "students7Desc5": "\t•\tThe curator is appointed and dismissed by the order of the rector / vice-rector for the state language and educational work of the IUMS on the proposal of the dean of the faculty / head of the department of educational and organizational-mass work, from among the most experienced teachers.\n",
        "students7Desc6": "\t•\tWorking with foreign students Each faculty has a responsible person - the faculty curator, who is directly subordinate to the dean of the faculty and the head of the department of educational and organizational-mass work.\n",
        "students7Desc7": "\t•\tThe curator is appointed and dismissed by the order of the rector / vice-rector for the state language and educational work of the IUMS on the proposal of the dean of the faculty / head of the department of educational and organizational-mass work, from among the most experienced teachers.\n",
        "students7Desc8": "\t•\tThe reception of foreign citizens from non-CIS countries is carried out directly by the official representative of the IUMS, who attracts foreign applicants for training. Al Madina Education Advisers works as representatives of IUMS and partners of IUMS on the basis of a signed cooperation agreement with IUMS, which gives it the right to recruit applicants for admission in accordance with the quota allocated by the Ministry of Foreign Affairs KR. Representatives of IUMS and partners of IUMS \"Al Madina Education Advisers\" apply for visa support for a foreign applicant, which is prepared by representatives of IUMS and partners of IUMS \"Al Madina Education Advisers\" and submitted to the Consular Service Department of the Ministry of Foreign Affairs of the Kyrgyz Republic. A foreign citizen applies to the Kyrgyz embassy in the country of origin to obtain a Kyrgyz study visa. After arriving in the Kyrgyz Republic, representatives of the IUMS and partners of the IUMS \"Al Madina Education Advisers\" help to collect the necessary documents for admission to the IUMS. After that, the foreign applicant is allowed to take the entrance exam, which is carried out by the method of blank testing with computer processing of the results or by passing the entrance exam orally. If a foreign applicant successfully passes the entrance examinations, he is admitted to study and a contract for training with the IUMS is concluded.\n",
    }
}
